const projects = [
  {
    id: 1,
    title: 'JAMQ',
    description: 'Make up artist portfolio',
    tags: 'React, Tailwind',
    link: 'https://jehanassi.fr/',
    imagePath: '/images/jamq.png',
  },
  {
    id: 2,
    title: 'Kinoklik',
    description: 'Full stack platform for filmmakers',
    tags: 'React, NodeJS, Express, MongoDB',
    link: 'https://www.kinoklik.ca/',
    imagePath: '/images/kinoklik.png',
  },
  {
    id: 3,
    title: 'LMS',
    description: 'Library Management System',
    tags: 'C#, WinForms, SQL',
    link: 'https://github.com/MalekGhazal/LMS-Project',
    imagePath: '/images/lms.png',
  },
  {
    id: 4,
    title: 'Web Application',
    description: 'Movie Reviews Website',
    tags: 'Java, React, Spring-boot',
    link: 'https://github.com/MalekGhazal',
    imagePath: '/images/movies.png',
  },
  {
    id: 5,
    title: 'E-commerce',
    description: 'MERN E-comm Website',
    tags: 'NodeJs, React, Express, MongoDB, Stripe',
    link: 'https://github.com/MalekGhazal/transactional-web-project-MalekGhazal',
    imagePath: '/images/ecomm.png',
  },
  {
    id: 6,
    title: 'Gopinion',
    description: 'Full Stack Admin Panel',
    tags: 'PHP, Laravel',
    link: 'https://gopinion.ca/admin/',
    imagePath: '/images/gopinion.png',
  },
  {
    id: 7,
    title: 'Portfolio-v1',
    description: 'My First Portfolio Ever',
    tags: 'HTML, CSS, JS',
    link: 'https://github.com/MalekGhazal/first-Portfolio',
    imagePath: '/images/portfolio-v1.png',
  },
  {
    id: 8,
    title: 'Portfolio-v2',
    description: 'My Second Portfolio',
    tags: 'HTML, CSS, SCSS, Bootstrap',
    link: 'https://github.com/MalekGhazal/second-Portfolio',
    imagePath: '/images/portfolio-v2.png',
  },
  {
    id: 9,
    title: 'Coming Soon...',
    description: 'Coming Soon ...',
    tags: 'PHP, Laravel, React',
    link: 'https://github.com/MalekGhazal',
    imagePath: '/images/laravel.png',
  },
];

export default projects;
